# Generated by Django 4.1.7 on 2025-04-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                (
                    "referral_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("registration_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referees",
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
